import { z } from "zod";

// Client-side schema used by react-hook-form
// No .default() here - defaults are set in the form's defaultValues
export const propertySchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  propertyType: z.enum(["RESIDENTIAL", "COMMERCIAL", "PLOT"]),
  listingType: z.enum(["SALE", "RENT"]),
  builderId: z.string().min(1, "Builder is required"),
  price: z.number().positive("Price must be positive"),
  priceUnit: z.enum(["LAKH", "CRORE"]),
  carpetArea: z.number().positive("Carpet area must be positive").optional().nullable(),
  carpetAreaUnit: z.enum(["SQFT", "SQYD", "SQMT"]).optional().nullable(),
  builtUpArea: z.number().positive("Built-up area must be positive").optional().nullable(),
  bedrooms: z.number().int().min(0, "Bedrooms must be 0 or greater").optional().nullable(),
  bathrooms: z.number().int().min(0, "Bathrooms must be 0 or greater").optional().nullable(),
  floorNumber: z.number().int().optional().nullable(),
  totalFloors: z.number().int().optional().nullable(),
  facingDirection: z.string().optional().nullable(),
  furnishing: z.enum(["UNFURNISHED", "SEMI_FURNISHED", "FULLY_FURNISHED"]).optional().nullable(),
  possessionStatus: z.enum(["READY_TO_MOVE", "UNDER_CONSTRUCTION", "UPCOMING"]),
  possessionDate: z.string().optional().nullable(),
  amenities: z.array(z.string()),
  address: z.string().optional().nullable(),
  city: z.string(),
  locality: z.string().optional().nullable(),
  state: z.string(),
  pincode: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  reraNumber: z.string().optional().nullable(),
  isFeatured: z.boolean(),
  isActive: z.boolean(),
});

export type PropertyFormData = z.infer<typeof propertySchema>;

// Server-side schema with coercion for numeric fields and defaults
export const propertyServerSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  propertyType: z.enum(["RESIDENTIAL", "COMMERCIAL", "PLOT"]),
  listingType: z.enum(["SALE", "RENT"]),
  builderId: z.string().min(1, "Builder is required"),
  price: z.coerce.number().positive("Price must be positive"),
  priceUnit: z.enum(["LAKH", "CRORE"]),
  carpetArea: z.coerce.number().positive("Carpet area must be positive").optional().nullable(),
  carpetAreaUnit: z.enum(["SQFT", "SQYD", "SQMT"]).optional().nullable(),
  builtUpArea: z.coerce.number().positive("Built-up area must be positive").optional().nullable(),
  bedrooms: z.coerce.number().int().min(0).optional().nullable(),
  bathrooms: z.coerce.number().int().min(0).optional().nullable(),
  floorNumber: z.coerce.number().int().optional().nullable(),
  totalFloors: z.coerce.number().int().optional().nullable(),
  facingDirection: z.string().optional().nullable(),
  furnishing: z.enum(["UNFURNISHED", "SEMI_FURNISHED", "FULLY_FURNISHED"]).optional().nullable(),
  possessionStatus: z.enum(["READY_TO_MOVE", "UNDER_CONSTRUCTION", "UPCOMING"]),
  possessionDate: z.string().optional().nullable(),
  amenities: z.array(z.string()).default([]),
  address: z.string().optional().nullable(),
  city: z.string().default("Bangalore"),
  locality: z.string().optional().nullable(),
  state: z.string().default("Karnataka"),
  pincode: z.string().optional().nullable(),
  latitude: z.coerce.number().optional().nullable(),
  longitude: z.coerce.number().optional().nullable(),
  reraNumber: z.string().optional().nullable(),
  isFeatured: z.boolean().default(false),
  isActive: z.boolean().default(true),
});
